DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "roles";
DROP TABLE IF EXISTS "subjects";
DROP TABLE IF EXISTS "user_subjects";
DROP TABLE IF EXISTS "assigments";
DROP TABLE IF EXISTS "solution";
DROP TABLE IF EXISTS "user_solution_assignments";
DROP TABLE IF EXISTS "microsoft_logins";
DROP TABLE IF EXISTS "session_refresh_keys";
